###############################################################################
# HeronAI ─ pre-commit configuration
#
# Each hook runs in an isolated virtual-env managed by pre-commit, ensuring
# consistent versions across machines and CI.
###############################################################################
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]
        additional_dependencies: [] # keep env lean
