repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]
        language_version: python3.11
        additional_dependencies:
          - "fastapi==0.111.0"
          - "pydantic==2.7.1"
          - "pydantic-settings==2.8.0"
          - "starlette==0.37.2"
          - "types-Flask==1.1.6"
          - "types-redis==4.6.0"
        files: ^src/
