version: "3.9"

volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # copy .env.example → .env and tweak if needed
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    command: >
      uvicorn src.api.app:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers
    restart: unless-stopped

  # 2. Redis – lightweight in-memory store for async jobs / rate-limiting
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  # 3. Postgres – future persistence layer (not used by runtime yet)
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
