global:
  scrape_interval: 5s # Default interval to scrape targets
  evaluation_interval: 5s

scrape_configs:
  - job_name: "document_classifier_service"
    honor_labels: true
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:8000"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
