# ============================================================================
# GitHub Actions – Continuous-Integration Workflow
# ============================================================================
# Lint ➜ Type-check ➜ Test (with coverage ≥ 95 %) ➜ Upload coverage artefact
# ============================================================================

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-test:
    name: "Lint ↦ Type-check ↦ Test (Python ${{ matrix.python-version }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      # -----------------------------------------------------
      # 1. Checkout source
      # -----------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------------------------
      # 2. Set-up Python with pip cache
      # -----------------------------------------------------
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # -----------------------------------------------------
      # 3. Install runtime + dev dependencies
      # -----------------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -----------------------------------------------------
      # 4. Ruff – static analysis & import-sorting
      # -----------------------------------------------------
      - name: Ruff lint
        run: ruff check .

      # -----------------------------------------------------
      # 5. Black – code formatting (verify only)
      # -----------------------------------------------------
      - name: Black formatting check
        run: black --check .

      # -----------------------------------------------------
      # 6. mypy – static type checking (strict mode)
      # -----------------------------------------------------
      - name: mypy type-check
        run: mypy --strict src

      # -----------------------------------------------------
      # 7. Pytest – unit & integration tests with coverage
      #     • Threshold enforced via pytest.ini (95 %)
      # -----------------------------------------------------
      - name: Run tests (with coverage)
        run: pytest -q

      # -----------------------------------------------------
      # 8. Upload coverage artefact (always runs for diagnostics)
      # -----------------------------------------------------
      - name: Upload coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
